// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdJA5aEXqdV3EGt4_kDy5BrSLbG5CaP44',
    appId: '1:819908586021:android:181d260b782a4a1525edcc',
    messagingSenderId: '819908586021',
    projectId: 'smartsocket-e5ba4',
    databaseURL: 'https://smartsocket-e5ba4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartsocket-e5ba4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE1eXDFqIO2V2jP-0fBOJFOL68ytHjZLc',
    appId: '1:819908586021:ios:7f0b9624770186cc25edcc',
    messagingSenderId: '819908586021',
    projectId: 'smartsocket-e5ba4',
    databaseURL: 'https://smartsocket-e5ba4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartsocket-e5ba4.firebasestorage.app',
    iosBundleId: 'com.srekntest.control',
  );
}
